import i18n from "i18n-js";

export const zwnj = "‌";

export default function initStrings(locale: string) {
    i18n.translations = {
        en: {
            messenger: "messenger",
            settings: "settings",
            explore: "explore",
            personalPage: "personal page",
            appName: "app-name",
            chats: "chats",
            allPosts: "All Posts",
            channelPosts: "Channel Posts",
            pages: "Pages",
            you: "You",
            posts: "Posts",
            following: "following",
            followers: "followers",
            messageBoxPlaceHolder: "Write your message here...",
            colorSettings: "Color Settings",
            primary: "primary",
            secondary: "secondary",
            save: "save",
            chosenColor: "chosen color:",
            chooseOneOfThese: "Choose one of these colors:",
            orCustomizeIt: "Or customize it...",
            search: "search",
            searchForTagsNamesAndContent: "Search for names, tags and content...",
            _todayChannelPost: "today 03:24 PM",
            language: "language",
            english: "English",
            persian: "فارسی",
            systemDefault: "System default",
            editProfile: "Edit Profile",
            insertName: "Insert Your Name Here",
            insertBio: "Insert Your Bio Here",
            insertUsername: "Insert Your Username Here",
            languageChange: "Language change",
            languageChanged:
                "Language changed. For styles and configurations to change correctly, a restart is required",
            restartNow: "Restart now",
            later: "Later",
            generalSettings: "General Settings",
            privacyAndSecurity: "Privacy And Security",
            optimizeImageToSaveData: "Optimize Image To Save Data",
            showPostsByPopularity: "Show Posts By Popularity",
            privateAccount: "Private Account",
            privateAccountNote: "people will seek permission to follow you",
            allowSaving: "Allow Saving",
            allowSavingNote: "people can save your post",
            post: "post",
            report: "report",
            reportedSuccessfully: "Reported successfully. Thanks.",
            sharePost: "Share post",
            comments: "comment(s)",
            viewAll: "view all",
            writeComment: "Write comment...",
            Save: "Save",
            Date: "Date",
            _justNow: "just now",
        },
        fa: {
            messenger: `پیام${zwnj}رسان`,
            settings: "تنظیمات",
            explore: "کاوش",
            personalPage: "صفحه شخصی",
            appName: "نام برنامه",
            chats: "مکالمات",
            allPosts: `تمامی پست${zwnj}ها`,
            channelPosts: `پست کانال${zwnj}ها`,
            pages: "صفحات",
            you: "شما",
            posts: `پست${zwnj}ها`,
            following: "دنبال شوندگان",
            followers: "دنبال کنندگان",
            messageBoxPlaceHolder: "پیام خود را وارد کنید...",
            colorSettings: "تنظیمات رنگ",
            save: "ذخیره",
            chosenColor: "رنگ انتخابی:",
            chooseOneOfThese: `یکی از رنگ${zwnj}های زیر را انتخاب کنید.`,
            orCustomizeIt: "یا به سلیقه خود تغییر دهید...",
            editProfile: "ویرایش پروفایل",
            insertName: "نام خود را اینجا وارد نمایید",
            insertBio: "بیو را اینجا وارد نمایید",
            insertUsername: "یوزنیم خود را اینجا وارد نمایید",
            search: "جستجو",
            searchForTagsNamesAndContent: `جستجو برای اشخاص، برچسب${zwnj}ها و محتوا...`,
            _todayChannelPost: "امروز 03:24 بعد از ظهر",
            english: "English",
            persian: "فارسی",
            systemDefault: "پیش فرض دستگاه",
            language: "زبان",
            languageChange: "تغییر زبان",
            languageChanged: "زبان تغییر کرد. برای تغییر صحیح تنظیمات و ظاهر، شروع مجدد نیاز است.",
            restartNow: "الان شروع مجدد کن.",
            later: "باشه بعداً",
            generalSettings: "تنظیمات عمومی",
            privacyAndSecurity: "حریم خصوصی و امنیت",
            showPostsByPopularity: "نمایش پست بر اساس محبوبیت",
            optimizeImageToSaveData: "بهینه سازی تصویر برای ذخیره داده ها",
            privateAccount: "حساب خصوصی",
            privateAccountNote: "دیگران برای دنبال کردن شما نیاز به اجازه دارند",
            allowSaving: "اجازه ی ذخیره سازی",
            allowSavingNote: "دیگران می توانند پست های شما را ذحیره کنند",
            post: "پست",
            report: "گزارش",
            reportedSuccessfully: "با موفقیت گزارش شد. ممنونیم.",
            sharePost: "اشتراک پست",
            comments: "نظر",
            viewAll: "نمایش همه",
            writeComment: "افزودن نظر...",
            _justNow: "همین الان",
            Save: "ذحیره",
            Date: "تاریح",
        },
    };

    i18n.locale = locale;

    i18n.fallbacks = true;
}
